---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prabhakarmishra/MSVirtualSession.git
          searchPaths: ConfigData
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:/offline-repository/         
          
server:
  port: 8001

rabbitmq:
    host: 192.168.99.100
    port: 5672
    cloud:
    bus:
      enabled: true
      destination: configXchangebus
      
spring.cloud.bus.enabled: true
management.endpoints.web.exposure.include: bus-refresh  
# For simplicity, disable security when posting to bus/refresh:  
management:
  security:
    enabled: false


   